# Generated by Django 5.1 on 2024-08-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_edrpou', models.CharField(max_length=10)),
                ('buyer_address', models.CharField(blank=True, max_length=200)),
                ('buyer_address_mail', models.CharField(blank=True, max_length=200)),
                ('buyer_req', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CultureName',
            fields=[
                ('culture_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_edrpou', models.CharField(max_length=10)),
                ('seller_address', models.CharField(blank=True, max_length=200)),
                ('seller_address_mail', models.CharField(blank=True, max_length=200)),
                ('seller_req', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_sname', models.CharField(max_length=100)),
                ('user_tel', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CultureActualPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('culture_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('culture_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.culturename')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dterms', models.CharField(blank=True, max_length=100)),
                ('quality', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_auto_dterms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_train_dterms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_dterms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('load_region', models.CharField(blank=True, max_length=100)),
                ('load_place', models.CharField(blank=True, max_length=100)),
                ('unload_region', models.CharField(blank=True, max_length=100)),
                ('unload_place', models.CharField(blank=True, max_length=100)),
                ('comment_user', models.TextField(blank=True)),
                ('comment_spoteks', models.TextField(blank=True)),
                ('sb', models.BooleanField(default=False)),
                ('docks', models.BooleanField(default=False)),
                ('dog', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('bd_culture_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.culturename')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
